apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-auth
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80