apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: myapp-db-deployment
  labels:
    app: myapp-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myapp-db
    spec:
      containers:
      - image: mysql:5.6
        name: myapp-db
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: DbPassword
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: myapp-db-pv-data