apiVersion: batch/v1
kind: Job
metadata:
  name: myapp-migration-job
spec:
  template:
    spec:
      containers:
      - name: myapp-migration
        image: lisitsynalex/myapp_migrator:1.2
        imagePullPolicy: Always
        env:
          - name: "ConnectionString"
            valueFrom:
              secretKeyRef:
                name: myapp-secrets
                key: ConnectionString
          - name: "DbName"
            valueFrom:
              configMapKeyRef:
                name: myapp-config
                key: dbname
      restartPolicy: Never
  backoffLimit: 4