{
 "title": "Backend metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "RPS - CreateUser",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(rps_summary_count{method_name=\"CreateUser\"}[$__interval])"
    }
   ]
  },
  {
   "title": "RPS - UpdateUser",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(rps_summary_count{method_name=\"UpdateUser\"}[$__interval])"
    }
   ]
  },
  {
   "title": "RPS - ReadUsers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(rps_summary_count{method_name=\"ReadUsers\"}[$__interval])"
    }
   ]
  },
  {
   "title": "RPS - DeleteUser",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "rate(rps_summary_count{method_name=\"DeleteUser\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Latency - CreateUser",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "elapsed_time_ms_summary{method_name=\"CreateUser\"}"
    }
   ]
  },
  {
   "title": "Latency - ReadUsers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "elapsed_time_ms_summary{method_name=\"ReadUsers\"}"
    }
   ]
  },
  {
   "title": "Latency - UpdateUser",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "elapsed_time_ms_summary{method_name=\"UpdateUser\"}"
    }
   ]
  },
  {
   "title": "Latency - DeleteUser",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "elapsed_time_ms_summary{method_name=\"DeleteUser\"}"
    }
   ]
  },
  {
   "title": "500 from app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    { "expr": "internal_server_error_counter" }
   ]
  }
 ]
}