apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-notifications-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-notifications
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80