config:
  dbname: "otusdb"

auth:
  image: "lisitsynalex/myapp_auth:hw5-lecture12"
  replicaCount: 1
  ASPNETCORE_APPL_PATH: '/auth'

backend:
  image: "lisitsynalex/myapp_backend:hw5-lecture12"
  replicaCount: 1
  ASPNETCORE_APPL_PATH: '/back'

migrator:
  image: "lisitsynalex/myapp_migrator:hw5-lecture12"

mysql:
  image: "mariadb:10.7.3"