apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-orders-deployment
  labels:
    app: {{ .Release.Name }}-orders
spec:
  replicas: {{ .Values.orders.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-orders
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-orders
    spec:
      containers:
        - name: {{ .Release.Name }}-orders
          image: {{ .Values.orders.image }}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            successThreshold: 3
          env:
            - name: "ASPNETCORE_APPL_PATH"
              value: {{ .Values.orders.ASPNETCORE_APPL_PATH }}          
            - name: "ConnectionString"
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: ConnectionString
            - name: "DbName"
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: dbname
          ports:
            - containerPort: 80
